runcmd:
# https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md#post-generation-scripts
- echo Post generation
- sudo su -c whoami ${user_name}
- '[ -d /opt/post-generation ] && sudo su -c "find /opt/post-generation -mindepth 1 -maxdepth 1 -type f -name *.sh -exec bash {} \;"'

final_message: "Post generation done after $UPTIME seconds"