bootcmd:

packages:
  # Core
  - apt-transport-https
  - ca-certificates
  - curl

write_files: 
  - path: /home/${user_name}/.config/powershell/setup_linux_vm.ps1
    encoding: base64
    content: ${setup_linux_vm_ps1}
    permissions: '0744'
  - path: /home/${user_name}/.config/powershell/environment.ps1
    encoding: base64
    content: ${environment_ps1}
    permissions: '0744'
  - path: /etc/environment
    content: |
      GEEKZTER_AGENT_SUBNET_ID="${subnet_id}"
      GEEKZTER_AGENT_VIRTUAL_NETWORK_HAS_GATEWAY="${virtual_network_has_gateway}"
      GEEKZTER_AGENT_VIRTUAL_NETWORK_ID="${virtual_network_id}"
    append: true

runcmd:
  # User configuration
  - chown -R ${user_name}:${user_name} /home/${user_name}
  - mkdir -p /home/${user_name}/src/bootstrap-os 2>/dev/null
  - git clone https://github.com/geekzter/bootstrap-os.git /home/${user_name}/src/bootstrap-os
  - cd /home/${user_name}/src/bootstrap-os/linux
  - git switch ${bootstrap_branch}
  - sudo ./bootstrap_linux2.sh ${bootstrap_switches}
  - chown -R ${user_name}:${user_name} /home/${user_name}
  - 'su -c "~/.config/powershell/setup_linux_vm.ps1" ${user_name}'
  # - '[ -d /opt/post-generation ] && sudo su -c "find /opt/post-generation -mindepth 1 -maxdepth 1 -type f -name *.sh -exec bash {} \;"'