bootcmd:
  # Disable automatic updates to get rid of the following race condition:
  #   Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
  # - sudo apt remove unattended-upgrades -y
  #- while ( fuser /var/lib/dpkg/lock >/dev/null 2>&1 ); do sleep 5; done;
  # Get apt repository signing keys
  # https://github.com/cli/cli/blob/trunk/docs/install_linux.md#installing-gh-on-linux-and-bsd
  - sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg # GitHub
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -           # Hashicorp
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -                  # Helm
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg # Kubernetes
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null # Microsoft

apt:
  sources:
    git-core:
      source: "ppa:git-core/ppa"
    github-cli.list:
      source: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    hashicorp:
      source: "deb [arch=amd64] https://apt.releases.hashicorp.com $RELEASE main"
    helm-stable-debian.list:
      source: "deb https://baltocdn.com/helm/stable/debian/ all main"
    kubernetes.list:
      source: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    microsoft-prod.list:
      source: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod $RELEASE main"

package_update: true
packages:
  # Core
  - apt-transport-https
  - ca-certificates
  - curl
  # - dirmngr
  - gnupg
  - lsb-release
  - software-properties-common
  - wget
  # Tools
  # - ansible
  - coreutils
  - dnsutils
  - docker
  - dos2unix
  - findutils
  # - fish
  # - fuse
  - git
  # - htop
  - jq
  # - less
  # - man
  - mc
  # - nano
  # - nmap
  - node-typescript
  - packer
  - python2-minimal
  - sed
  - snapd
  - telnet
  - terraform
  - tmux
  - traceroute
  - tree
  - unixodbc-dev
  - unzip
  - wget
  - whois
  # GitHub
  - gh
  # Kubernetes
  - helm
  - kubectl
  # Microsoft
  - azure-functions-core-tools-3
  # - blobfuse
  - dotnet-sdk-6.0
  # - dotnet-sdk-8.0
  # - msodbcsql17
  # - mssql-tools
  - powershell

runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - sudo ACCEPT_EULA=Y apt install msodbcsql17 -y
  - sudo ACCEPT_EULA=Y apt install mssql-tools -y
  - echo Installing PowerShell modules...
  - sudo pwsh -NoProfile -NonInteractive -Command 'Install-Module -Name Az,AzureAD,Oh-My-Posh,Posh-Git,PSReadLine,SqlServer,Terminal-Icons -Scope AllUsers -Repository PSGallery -Force'
  - echo Installing azcopy...
  - 'wget -O - https://aka.ms/downloadazcopy-v10-linux | tar xzf - --strip-components=1 -C /tmp'
  - mv /tmp/azcopy /usr/local/bin/azcopy
  - chmod +x /usr/local/bin/azcopy
  # https://aka.ms/downloadazcopy-v10-linux
  - sudo apt install unattended-upgrades -y

final_message: "Tools installed after $UPTIME seconds"